### ISSUE TITLE
Make Photos fill squares

### ISSUE THREAD

**Issue by tedbarnett** [tedbarnett/My-Photo-Reviewer#13]
When viewing photos in the grid (ie not when choosing albums), make sure each photo "fills" the square it is in, even if some parts of the photo are hidden. Copy how Apple Photos handles this:

**Comment by tedbarnett** [comment]
Current style (wasted space):
![image](https://github.com/tedbarnett/My-Photo-Reviewer/assets/694013/4b4b84d1-a5db-4d97-b938-0c744ca2b186)

**Comment by tedbarnett** [comment]
Preferred style (no wasted space):

**Comment by tedbarnett** [comment]
![image](https://github.com/tedbarnett/My-Photo-Reviewer/assets/694013/726f7a7d-fd50-43b7-93dd-d920254f0f73)

**Comment by prempratapsingh** [comment]
Done! The photos are matching with Apple's layout style. This change will be available in the next build version 0.2 build 17
![IMG_4853](https://github.com/tedbarnett/My-Photo-Reviewer/assets/27926337/bc4f602e-276b-4ca3-a6f7-33cd3740df8f)

**Comment by tedbarnett** [comment]
Nice!
