### ISSUE TITLE
Slide show should only show annotated photos

### ISSUE THREAD

**Issue by tedbarnett** [tedbarnett/My-Photo-Reviewer#5]
If a photo has no audio and the date and location have not been changed, skip it in the slide show. In other words, only show slides the user has edited in some way.

**Comment by prempratapsingh** [comment]
Makes sense!
Should a photo be shown, if it has no audio added but either of location or date updated for it?

**Comment by prempratapsingh** [comment]
This is done!
Now only those photos will show up in slide show which user would have added audio recording or updated location/date EXIF details.

**Comment by tedbarnett** [comment]
Good call: include photo if any edits are made (audio or date or location)
