### ISSUE TITLE
Fix Apple Photos selection window

### ISSUE THREAD

**Issue by tedbarnett** [tedbarnett/My-Photo-Reviewer#8]
This page looks amateurish and unfinished. No title. Icon spacing way too far. Should be a tighter list with icons and date created. Replace buttons with proper Apple UI. Look at Apple Photos or any modern photo app. 

![image](https://github.com/tedbarnett/My-Photo-Reviewer/assets/694013/2f002fb0-d317-41c1-99de-e2111e6c8713)

**Comment by prempratapsingh** [comment]
Updated the album/folder selection view to make it look compact and similar to the iOS album selection view.

**Comment by tedbarnett** [comment]
Much better!
